name: datetimes
version: '0.1.0.0'
author: Adjoint Inc
license: MIT
dependencies:
- base ==4.9.*
- protolude >=0.2
- hourglass >=0.2
- aeson >=1.2
- cereal >=0.5
library:
  source-dirs: src
  ghc-options:
    -fwarn-unused-imports
    -fwarn-incomplete-patterns
  exposed-modules:
  - Main
  - Types
  - Holiday
