name: datetimes
version: '0.1.0.0'
author: Adjoint Inc
license: MIT
dependencies:
- base >= 4.7 && < 5
- protolude >=0.2
- hourglass >=0.2
- aeson >=1.1
- cereal >=0.5
library:
  source-dirs: src
  ghc-options:
    -fwarn-unused-imports
    -fwarn-incomplete-patterns
    -fwarn-incomplete-uni-patterns
  exposed-modules:
  - Main
  - Holiday
  - Holiday.Types

tests:
  matrix-test:
    dependencies:
    - base >= 4.7
    - protolude >= 0.2
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    main: Test.hs
    source-dirs: test
